# DNSweeper PDCA Configuration
# PDCAサイクル自動化の設定ファイル

# 基本設定
pdca:
  version: "1.0.0"
  project: "dnsweeper-cli"
  
# 自動化レベル
automation:
  level: "BASIC"  # NONE | BASIC | FULL
  
  # 日次PDCA設定
  daily:
    enabled: true
    schedule: "0 9 * * *"  # 毎日9:00 JST
    notify_on_failure: true
    auto_create_issues: false
    max_execution_time: "5m"
    
  # 週次PDCA設定
  weekly:
    enabled: true
    schedule: "0 10 * * 5"  # 毎週金曜10:00 JST
    auto_generate_report: true
    ai_insights: false  # 有料プラン後に有効化
    max_execution_time: "15m"
    
  # リリースPDCA設定
  release:
    enabled: true
    auto_changelog: true
    auto_version_bump: false
    quality_gates:
      test_coverage: 90
      build_success: true
      no_critical_issues: true
      
  # 緊急PDCA設定
  alerts:
    enabled: true
    severity_threshold: "HIGH"
    auto_rollback: false
    notification_channels:
      - github_issues
      # - slack  # Webhook設定後に有効化

# メトリクス設定
metrics:
  # DORAメトリクス目標値
  dora:
    deployment_frequency: "3 per week"
    lead_time: "2 days"
    mttr: "30 minutes"
    change_failure_rate: "10%"
    
  # DNSweeper固有メトリクス
  custom:
    test_coverage: "90%"
    memory_usage: "50MB"
    processing_speed: "200k records/sec"
    npm_weekly_growth: "10%"

# 実験設定
experiments:
  enabled: true
  concurrent_experiments: 2
  success_criteria:
    performance_improvement: "20%"
    user_satisfaction: "80%"
    
# 通知設定
notifications:
  github:
    enabled: true
    create_issues: true
    assign_to: ["@maintainer"]
    
  slack:
    enabled: false  # Webhook設定後に有効化
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channels:
      daily: "#dnssweeper-daily"
      weekly: "#dnssweeper-weekly"
      alerts: "#dnssweeper-alerts"

# Claude動作設定
claude:
  mode: "QUALITY_FIRST"
  language: "ja"
  error_handling:
    zero_tolerance: true
    auto_fix: true
  testing:
    always_run: true
    coverage_threshold: 90
  commit:
    auto_commit: false
    conventional_style: true

# レポート設定
reports:
  format: "markdown"
  storage:
    location: ".pdca/"
    retention_days: 90
  include:
    - metrics_summary
    - test_results
    - performance_data
    - improvement_suggestions
    
# セキュリティ設定
security:
  dependency_check: true
  vulnerability_threshold: "MODERATE"
  auto_update_patches: false
  
# 環境別設定
environments:
  development:
    automation_level: "FULL"
    notifications: false
    
  production:
    automation_level: "BASIC"
    notifications: true
    quality_gates_strict: true