# DNSweeper 自律モード設定ファイル
# ==========================================

autonomous_mode:
  # 基本設定
  # ---------------------------------------
  enabled: true
  version: "1.0.0"
  max_execution_time: "24h"
  max_queue_size: 50
  approval_timeout: "24h"
  auto_save_interval: "5m"
  
  # タスク選択設定
  # ---------------------------------------
  task_selection:
    prefer_independent: true
    risk_tolerance: "medium"              # low/medium/high
    creativity_level: "balanced"          # conservative/balanced/creative
    learning_enabled: true
    dependency_analysis: true
    
  # 自動承認設定
  # ---------------------------------------
  auto_approve:
    low_risk_readonly: true
    test_commands: true
    documentation_updates: true
    code_analysis: true
    lint_fixes: true
    
  # 時間帯別設定
  # ---------------------------------------
  time_based_rules:
    night_mode:
      hours: "22-06"
      risk_level: "low"
      experimental: true
      preferred_tasks:
        - "documentation_update"
        - "code_cleanup"
        - "test_enhancement"
        - "performance_analysis"
      avoided_tasks:
        - "production_deployment"
        - "database_migration"
        - "critical_bug_fix"
        
    day_mode:
      hours: "09-18"
      risk_level: "medium"
      approval_strategy: "queue"
      conservative: true
      preferred_tasks:
        - "bug_investigation"
        - "test_creation"
        - "refactoring"
        - "code_analysis"
      
    weekend_mode:
      days: ["saturday", "sunday"]
      risk_level: "low"
      experimental: true
      focus_areas:
        - "experimental_features"
        - "performance_optimization"
        - "documentation"
        
  # 通知設定
  # ---------------------------------------
  notifications:
    queue_threshold: 10
    completion_summary: true
    critical_alerts: true
    progress_updates: true
    email_notifications: false
    
  # 学習システム設定
  # ---------------------------------------
  learning:
    pattern_recognition: true
    success_tracking: true
    failure_analysis: true
    optimization_interval: "1d"
    history_retention: "30d"
    
  # セキュリティ設定
  # ---------------------------------------
  security:
    require_approval_for:
      - "file_deletion"
      - "external_api_calls"
      - "system_commands"
      - "production_changes"
    
    prohibited_operations:
      - "rm -rf"
      - "format"
      - "delete database"
      - "drop table"
      
    safe_directories:
      - "/mnt/c/projects/dnssweeper-cli/src"
      - "/mnt/c/projects/dnssweeper-cli/test"
      - "/mnt/c/projects/dnssweeper-cli/docs"
      
# キュー管理設定
# ==========================================
queue_management:
  # 表示設定
  display:
    max_items_per_page: 20
    show_timestamps: true
    show_dependencies: true
    color_coding: true
    group_by_category: true
    
  # 承認設定
  approval:
    require_confirmation: true
    batch_size_limit: 50
    confirmation_timeout: "30s"
    
  # フィルタ設定
  filters:
    default_time_range: "24h"
    favorite_filters:
      - name: "今日の低リスク"
        filter: 
          riskLevel: "low"
          timeRange: "1d"
      - name: "実装タスク"
        filter:
          category: "implementation"
      - name: "テスト関連"
        filter:
          category: "testing"
          
  # 自動処理設定
  auto_processing:
    enabled: true
    low_risk_auto_approve: true
    high_risk_auto_reject: false
    outdated_task_cleanup: true
    cleanup_after_days: 7

# 4フェーズ実行設定
# ==========================================
phases:
  investigate:
    default_duration: "10m"
    max_duration: "30m"
    auto_save_interval: "2m"
    tools:
      - "code_analysis"
      - "dependency_check"
      - "performance_profile"
      - "security_scan"
      
  plan:
    default_duration: "5m"
    max_duration: "15m"
    require_approval: false
    validation_rules:
      - "no_breaking_changes"
      - "backward_compatibility"
      - "test_coverage_maintained"
      
  implement:
    default_duration: "20m"
    max_duration: "60m"
    checkpoint_interval: "5m"
    rollback_enabled: true
    testing_required: true
    
  test:
    default_duration: "10m"
    max_duration: "30m"
    required_coverage: 80
    auto_fix_enabled: true
    regression_testing: true

# 依存関係管理
# ==========================================
dependencies:
  analysis_enabled: true
  cache_duration: "1h"
  
  # タスク関係定義
  task_relationships:
    implementation:
      requires: ["investigation", "planning"]
      blocks: ["deployment"]
      
    testing:
      requires: ["implementation"]
      enables: ["deployment", "release"]
      
    documentation:
      independent: true
      low_priority: true
      
    refactoring:
      requires: ["testing"]
      blocks: ["new_features"]

# ログ・監視設定
# ==========================================
logging:
  level: "info"                    # debug/info/warn/error
  file: ".dza/autonomous.log"
  max_size: "100MB"
  rotate: true
  retention: "30d"
  
monitoring:
  enabled: true
  metrics_collection: true
  performance_tracking: true
  error_tracking: true
  
  alerts:
    queue_overflow: true
    execution_timeout: true
    critical_errors: true
    security_violations: true

# バックアップ・復旧設定
# ==========================================
backup:
  enabled: true
  interval: "1h"
  retention: "7d"
  location: ".dza/backups"
  
recovery:
  auto_recovery: true
  checkpoint_validation: true
  rollback_on_failure: true